#!/bin/bash
# weekly-review.sh — Jeff's weekly review ritual
# Run Fridays (evening) or Saturdays (morning) — or anytime Jeff wants a clean slate.
# Targets: Todoist cleanup + week summary + week preview + memory log

set -e

WORKSPACE="/Users/Jeff/.openclaw/workspaces/main"
TODOIST_BIN="$HOME/.npm-global/bin/todoist"
VAULT_DIR="$HOME/Library/CloudStorage/OneDrive-Personal/Apps/remotely-save/Wuttipong Vault"

TODAY=$(date +"%Y-%m-%d")
WEEK_END=$(date +"%A, %B %d")
WEEK_START=$(date -v-6d +"%Y-%m-%d")
WEEK_START_DISPLAY=$(date -v-6d +"%A, %B %d")

echo "🧹 Weekly Review — Jeff"
echo "⏰ $(TZ='Asia/Bangkok' date +'%I:%M %p') (Bangkok)"
echo ""
echo "========================================"

# ── 1. WEEK SUMMARY FROM OBSIDIAN ────────────────────
echo ""
echo "📓 WEEK IN REVIEW — $WEEK_START_DISPLAY → $WEEK_END"
echo "----------------------------------------"

MEMORY_DIR="$WORKSPACE/memory"
WEEK_START_EPOCH=$(date -v-6d +%s)
WEEK_END_EPOCH=$(date +%s)

# Find memory files from past 7 days by mtime
WEEK_FILES=$(find "$MEMORY_DIR" -name "2026-*.md" -type f 2>/dev/null | while read f; do
  FILE_EPOCH=$(stat -f %m "$f" 2>/dev/null || stat -c %Y "$f" 2>/dev/null)
  if [ "$FILE_EPOCH" -ge "$WEEK_START_EPOCH" ]; then
    echo "$f"
  fi
done | sort)
if [ -n "$WEEK_FILES" ]; then
  echo "Memory notes from this week:"
  for f in $WEEK_FILES; do
    NOTE_NAME=$(basename "$f")
    # Extract non-heading lines for context
    LINES=$(grep -v "^#" "$f" 2>/dev/null | grep -v "^--" | grep -v "^$" | head -3)
    if [ -n "$LINES" ]; then
      echo "  📌 $NOTE_NAME"
      echo "$LINES" | sed 's/^/     /'
    fi
  done
else
  echo "(no memory files found for this week)"
fi

# ── 2. TODOIST TASK AUDIT ─────────────────────────────
echo ""
echo "✅ TODOIST AUDIT — Stale & Overdue"
echo "----------------------------------------"

if [ -f "$TODOIST_BIN" ] || command -v todoist &>/dev/null;
then
  TODOIST_BIN="${TODOIST_BIN:-$HOME/.npm-global/bin/todoist}"
  ALL_TASKS=$("$TODOIST_BIN" tasks 2>/dev/null || echo "")

  # Show overdue + stale onboarding tasks
  TODAY_STR=$(date +"%Y-%m-%d")
  echo "⚠️  Overdue / stale tasks:"
  echo "$ALL_TASKS" | head -20

  # Count July onboarding cruft (Todoist onboarding creates these in Jul)
  CRUFT=$(echo "$ALL_TASKS" | grep -iE "(onboarding|getting started|productivity method quiz|free apps and plugins|getting started guide)" | grep -c "Jul" || echo "0")
  echo ""
  echo "→ $CRUFT onboarding tasks detected (created Jul — likely obsolete)"

  if [ "$CRUFT" -gt 0 ]; then
    echo "  Suggested action: delete these 6 onboarding tasks?"
    echo "  Run: todoist delete <task_id> for each, or open Todoist app"
    echo ""
    echo "  Task IDs:"
    echo "$ALL_TASKS" | grep -iE "(onboarding|getting started|productivity method|free apps)" | grep "Jul" | awk '{print "  •", $1}'
  fi
else
  echo "(Todoist CLI not found)"
fi

# ── 3. WEEK AHEAD — CALENDAR ────────────────────────
echo ""
echo "📅 WEEK AHEAD — $(date -v+1d +'%b %d') → $(date -v+6d +'%b %d')"
echo "----------------------------------------"

CAL_FOUND=0
if command -v gog &>/dev/null; then
  # gog calendar events uses --from/--to ISO timestamps
  WEEK_EVENTS=$(gog calendar events \
    --from "$(date -v+1d -u +'%Y-%m-%dT00:00:00Z')" \
    --to "$(date -v+7d -u +'%Y-%m-%dT23:59:59Z')" 2>/dev/null | head -30)
  if [ -n "$WEEK_EVENTS" ]; then
    echo "$WEEK_EVENTS"
    CAL_FOUND=1
  fi
fi

if [ "$CAL_FOUND" -eq 0 ]; then
  echo "(gog calendar not yet connected — set up Google Calendar integration)"
fi

# ── 4. THIS WEEK'S WINS ──────────────────────────────
echo ""
echo "🌟 THIS WEEK'S WINS"
echo "----------------------------------------"
echo "What made this week a win? (one per line, empty line to finish)"
WIN_LINE=""
while true; do
  read -r -p "> " LINE
  if [ -z "$LINE" ]; then
    break
  fi
  WIN_LINE="${WIN_LINE}• ${LINE}"$'\n'
done

# ── 5. NEXT WEEK'S TOP 3 PRIORITIES ─────────────────
echo ""
echo "🎯 NEXT WEEK — Top 3 Priorities"
echo "----------------------------------------"
echo "What must get done next week? (one per line, empty line to finish)"
PRIORITIES=""
while true; do
  read -r -p "> " LINE
  if [ -z "$LINE" ]; then
    break
  fi
  PRIORITIES="${PRIORITIES}• ${LINE}"$'\n'
done

# ── SAVE TO MEMORY ──────────────────────────────────
echo ""
echo "💾 SAVING TO MEMORY..."
REVIEW_FILE="$WORKSPACE/memory/weekly-review-$(date +'%Y-%m-%d').md"
NEXT_MONDAY=$(date -v+1d +'%Y-%m-%d')
NEXT_SUNDAY=$(date -v+7d +'%Y-%m-%d')

cat > "$REVIEW_FILE" << EOF
# Weekly Review — $(date +'%A, %B %d, %Y')

## 🏆 This Week's Wins
$WIN_LINE

## 🎯 Next Week's Priorities ($NEXT_MONDAY → $NEXT_SUNDAY)
$PRIORITIES

## 📓 Week in Review
$(for f in $WEEK_FILES; do echo "- $(basename $f)"; done)

## ✅ Todoist Audit Notes
$(echo "$ALL_TASKS" | head -20 | sed 's/^/  /')

---
_Generated by Smith weekly-review skill_
EOF

echo "✓ Saved to: weekly-review-$(date +'%Y-%m-%d').md"

# ── CLOSING ─────────────────────────────────────────
echo ""
echo "========================================"
echo "🧹 Week's clean. Let's make next week count, Jeff."
echo "Review complete — $(TZ='Asia/Bangkok' date +'%I:%M %p')"